name: docker-builds 

on:
  push:
    branches:
      - 'develop'
    # Run the workflow once a week
  schedule: 
    - cron:  '0 0 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Develop
        uses: docker/build-push-action@v3
        with:
          context: .devcontainer
          push: true
          tags: attachix/sming:develop
      -
        name: Build and push GitPod
        uses: docker/build-push-action@v3
        with:
          context: .devcontainer
          build-args: "CONTAINER_USER=gitpod"
          push: true
          tags: attachix/sming:develop_gitpod
